services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: rfid-broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto-config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto-data:/mosquitto/data
      - ./mosquitto-log:/mosquitto/log
    restart: always

  mqtt-explorer:
    image: smeagolworms4/mqtt-explorer:latest
    container_name: mqtt-explorer-ui
    ports:
      - "4000:80"
    environment:
      - HTTP_PORT=80
    volumes:
      - ./explorer-data:/tmp  # Aquí es donde la imagen de smeagol suele guardar config
    depends_on:
      - mosquitto
    restart: always